#Introduction to Python

# Variables and Data Types
* Variables are dynammically typed. No need to write data type while declaring a variable.

In [ ]:
#Declaring variables

a = 123           #integer
b = 1.23          #float
c = 1 + 2j        #complex
d = "Hello World" #string
e = True          #boolean true
f =  False        #boolean false

In [ ]:
#Printing the variables

print (a)
print (b)
print (c)         #Bracket for complex number
print (d)
print (e)

123
1.23
(1+2j)
Hello World
True


In [ ]:
#Checking types

type(c)

complex

In [ ]:
#Basic arithmetic operations

print (5 + 2)
print (5 - 2)
print (5 * 2)
print (5 / 2)
print (5 % 2)     #Mod operator. Returns remainder
print (2 ** 4)    #Power

7
3
10
2.5
1
16


In [ ]:
print (5 / 3)
print (5 // 3)    #Returns only the Integer part

1.6666666666666667
1


In [ ]:
print ("The current value of a is", a)            #Concatenated using comma
print ("The current value of a is", a, "and b is", b)

The current value of a is 123
The current value of a is 123 and b is 1.23


In [ ]:
print ("The current value of a is", a)            #Default blank space
print ("The current value of a is", a, sep = '...')  #Customize using separator

The current value of a is 123
The current value of a is...123


In [ ]:
print ("The current value of a is", a)          #Auto newline added. If we don't need any newline, keep it blank
print ("The current value of a is", a, end = "\n\n")
print ("Hello")

The current value of a is 123
The current value of a is 123

Hello


# String

In [ ]:
#String Concatenation
x = "Hi!"
y = "My name is Suhit"
z = x + y
print (z)

Hi!My name is Suhit


In [ ]:
#Accessing String with character position number. Space is also a character
print (y[0])
print (y[5])

M
m


In [ ]:
#Length of the String
print (len(x))

3


In [ ]:
#Acsessing Last Character
print (y[len(y)-1])
print(y[-1])

t
t


In [ ]:
#Common String Methods
s = "My name is Suhit"

print (y.upper())   #All uppercase
print (y.lower())   #All lowercase
print (y.title())   #Title case - Every word first letter uppercase

MY NAME IS SUHIT
my name is suhit
My Name Is Suhit


In [ ]:
s = "   My name is Suhit"
print (y.strip())   #Strips spaces from starting or ending positions
print (y.strip().title())   #Combination of multiple methods - works sequentially

My name is Suhit
My Name Is Suhit


In [ ]:
s = "My name is Suhit"
print (y.find("is"))    #Returns the position of the 1st letter of the intended word
print (y.find("hello")) #Not in the string
print (y.find ("a"))    #Returns 1st appearence position of the intended letter

8
-1
4


In [ ]:
#Membership Operator. Returns Boolean
"Suhit" in s

True

In [ ]:
#Replace method
m = "My name is Sahib"
m_new = m.replace("Sahib", "Suhit")
print(m)
print (m_new)

My name is Sahib
My name is Suhit


In [ ]:
#String Slicing
s = "I love watching Cricket!"

#m[a:b] -> Return from index a up until index b (b not included)
print (s[0:5])

I lov


In [ ]:
print (s[:5])
print (s[5:])

I lov
e watching Cricket!


In [ ]:
print (s[-4:])
print(s[-1::-1])

ket!
!tekcirC gnihctaw evol I


# User Input

In [ ]:
username = input("Enter username:")
print("Username is: " + username)

Enter username:Suhit
Username is: Suhit


In [ ]:
num = int(input("Enter number:"))  #Take user input as string. Need to type cast to use the numbers
print (num * 2)

Enter number:4
8


# Conditional Statements

In [ ]:
x = 5
y = 6

if x > y:
  print("Maximum is x")
else:
  print ("Maximum is y")

Maximum is y


In [ ]:
#elif
x = 5
y = 5

if x > y:
  print("Maximum is x")
elif x == y:
  print ("x and y are equal")
else:
  print ("Maximum is y")

x and y are equal


In [ ]:
#and - Both conditions need to be True
a = 200
b = 10
c = 500
if a > b and c > a:
  print("Both conditions are True")
else:
  print("Negative!!")

Both conditions are True


In [ ]:
#or - Either one of the conditions = True should be enough
a = 200
b = 10
c = 500
if a > b or a > c:
  print("At least one of the conditions is True")
else:
  print("Negative!!")

At least one of the conditions is True


In [ ]:
#Nested if
x = 50

if x > 10:
  print("Above ten!")
  if x > 20:
    print("and also above 20!")
  else:
    print("but not above 20!")
else:
  print("Not even above ten!")

Above ten!
and also above 20!


In [ ]:
#pass statement - Can not leave any block blank. Use pass

a = 10
b = 20

if b > a:
  pass

# Python Built-in Data Types

#List
* Similar to Java or C array
* Collection of elements of multiple data types
* Allows easy modification of data
* Requires more memory to store additional information about data types of each element

In [ ]:
#Initializing
list = [1, 2, 3, 4, 5]
print(list)

[1, 2, 3, 4, 5]


In [ ]:
mixed_list = [1, 2.5, "hello", [1, 2, 3]]
print(mixed_list[3])

[1, 2, 3]


In [ ]:
#List Methods
print(len(list))
print(4 in list)    #Search

list[2] = "New"     #Update value
print(list)

list.append("World")    #Add new element
print(list)


5
True
[1, 2, 'New', 4, 5]
[1, 2, 'New', 4, 5, 'World']


In [ ]:
list.remove("New")    #Remove element
print(list)
list.pop(1)           #Remove using index
print(list)

list2 = [16, 55]
joined_list = list + list2
print(joined_list)

[1, 2, 4, 5, 'World']
[1, 4, 5, 'World']
[1, 4, 5, 'World', 16, 55]


In [ ]:
my_list = ['a', 'b', 'c', 'd', 'e', 'f']

In [ ]:
#List Slicing

print (my_list[3])
print (my_list[1:3])
print (my_list[:3])
print (my_list[3:])
print (my_list[-3:])

d
['b', 'c']
['a', 'b', 'c']
['d', 'e', 'f']
['d', 'e', 'f']


In [ ]:
print (my_list[0:4:2])      #index+2 everytime
print (my_list[:])          #All elements
print (my_list[::2])
print (my_list[::-1])       #Reverse order

['a', 'c']
['a', 'b', 'c', 'd', 'e', 'f']
['a', 'c', 'e']
['f', 'e', 'd', 'c', 'b', 'a']


In [ ]:
#Print last 4 elements in reverse
my_list = ['a', 'b', 'c', 'd', 'e', 'f']

print (my_list[-1:-5:-1])
print (my_list[-1:-5:1])

['f', 'e', 'd', 'c']
[]


In [ ]:
#print 2nd to 5th element reverse order
print (my_list[4:0:-1])

['e', 'd', 'c', 'b']


In [ ]:
#Matrix [List of list] using list
matrix = [[1, 2, 3, 4],
          [5, 6, 7, 8]]

# |1 2 3 4|
# |5 6 7 8|

print (matrix[1][2])

7


# Tuple
* Immutable - Items can not be modified
* Collection of elements of multiple data types

In [ ]:
tuple = (1, 2, 3, 4, 5)
tuple[0]

1

In [ ]:
tuple[1] = "hello"

TypeError: 'tuple' object does not support item assignment

#Set
* Immutable - Items can not be modified
* Unordered - No index
* No duplicates allowed

In [ ]:
set = {"apple", "banana", "cherry", "banana"}
print(set)

In [ ]:
set.add("orange")
print(set)

set.remove("banana")
print(set)

# Dictionary
* Values stored as key:value pair
* Mutable
* Key can be of any types but can not be a duplicate value

In [ ]:
cricketers = {
    75: "Shakib",
    2: "Mashrafee",
    28: "Tamim",
    "Extra": "Riad"
}

print(cricketers)

In [ ]:
print(cricketers["Extra"])      #Accessing elements
print(cricketers[2])

cricketers["Extra"] = "Mahmudullah"
print(cricketers)

cricketers.update({15:"Mushfiq"})
print(cricketers)

cricketers.pop("Extra")
print(cricketers)

# Loops
* 2 types - while loop and for loop

In [ ]:
#while loop
i = 0
while i < 10:
    print(i)
    i = i + 1

In [ ]:
#for loop
for i in range(0, 10,2):
  print(i)

In [ ]:
# Iterate over the list
list = ['a', 'b', 'c', 'd', 'e']

for i in list:
  print (i)

In [ ]:
# Program to iterate through a list using indexing
list = ['a', 'b', 'c', 'd', 'e']

# iterate over the list using index
for i in range(0, len(list)):
    print("index =", i, "value =", list[i])

for i,j in enumerate(list):
  print (i,j)

In [ ]:
#break statement - Out of the loop
fruits = ["apple", "banana", "cherry"]
for x in fruits:
  print(x)
  if x == "banana":
    break

In [ ]:
#continue statement - Stop the current iteration of the loop and continue with the next
fruits = ["apple", "banana", "cherry"]
for i in fruits:
  if i == "banana":
    continue
  print(i)

In [ ]:
#Nested loop
num_list = [1, 2, 3]
alphabet_list = ['a', 'b', 'c']

for number in num_list:
    print(number)
    for letter in alphabet_list:
        print(letter)

# Functions

In [ ]:
def hello_function():
  print("Hello")

hello_function()      #Global Scope

In [ ]:
#With parameter
def name_function(fname, lname):
  print(fname, " ", lname)

name_function("Anika", "Mrittika")

In [ ]:
#With return statement
def sum_numbers(number1, number2):
  result = number1+number2
  return result

x = sum_numbers(2, 3)
print (x)

In [ ]:
#Default Parameter Value
def increment(number, by=1):
    return number + by

print(increment(2))
print(increment(2, 5))

# Keyword arguments
print(increment(by=10, number=25))

In [ ]:
#If the number of arguments is unknown, add a * before the parameter name. Stored as a Tuple
def print_student_list(*kids):
  for x in kids:
    print (x)

print_student_list("Emil", "Tobias", "Linus")

# Numpy
* A Python library
* Used for working with arrays
* Short form of "Numerical Python"
* Aims to provide an array object that is up to 50x faster than traditional Python lists
* Provides a lot of supporting functions

In [ ]:
import numpy as np

In [ ]:
arr = np.array([1 , 2, 3, 2.45, "hello"])
print(arr)

print(type(arr))

['1' '2' '3' '2.45' 'hello']
<class 'numpy.ndarray'>


In [ ]:
print(len(arr))

5


In [ ]:
#Append
x = np.array([1, 2, 3, 4, 5])
y = np.append(x,50)
z = np.append(y, [30, 70])
print(y)
print(z)
print(x) #No change in main array

[ 1  2  3  4  5 50]
[ 1  2  3  4  5 50 30 70]
[1 2 3 4 5]


In [ ]:
#Delete
x = np.array([1, 2, 3, 4, 5])
y = np.delete(x, 2)   #Delete using index
print(x)
print(y)

[1 2 3 4 5]
[1 2 4 5]


In [ ]:
#Sorting
x = np.array([7, 8, 3, 10, 5])
sorted_x = np.sort(x)
print(sorted_x)     #Ascending
y= sorted_x[::-1]
print(y)   #Descending - Reverse the Ascending order sorted array

[ 3  5  7  8 10]
[10  8  7  5  3]


In [ ]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6],[7, 8, 9]])
print(arr_2d)



[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
print(len(arr_2d))
print(arr_2d.shape)     #row, column
print(arr_2d.ndim)      #Dimension

3
(3, 3)
2


In [ ]:
#indexing
arr = np.array([1, 2, 3, 4])

print(arr[0])     #1st element
print(arr[-1])    #Last element

1
4


In [ ]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr)

print('5th element on 2nd row: ', arr[1, 4])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
5th element on 2nd row:  10


In [ ]:
#Slicing
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[4:])
print(arr[:4])
print(arr[-3:-1])
print(arr[1:5:2])

[5 6 7]
[1 2 3 4]
[5 6]
[2 4]


In [ ]:
#Slicing 2-D Arrays
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

#From the second row, slice elements from index 1 to index 4 (not included)
print(arr[1, 1:4])
print()
#From both rows, slice index 1 to index 4 (not included)
print(arr[0:2, 1:4])

[7 8 9]

[[2 3 4]
 [7 8 9]]


In [ ]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print (arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [ ]:
print(arr[:, 0])    #column
print(arr[0, :])    #row

[1 6]
[1 2 3 4 5]


In [ ]:
#zero matrix
x = np.zeros(5)
print(x)

y = np.zeros(5,dtype=int)
print(y)

[0. 0. 0. 0. 0.]
[0 0 0 0 0]


In [ ]:
y = np.zeros((4,2))     #row, column
print(y)

print()
print()

z = np.zeros((3,3),dtype=int)     #row, column
print(z)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [ ]:
a = np.array([3, 4, 5])
b = np.array([[1,2,3],[4,5,6]])

print(np.sum(a))      #Summation of all elements
print(np.prod(a))     #Product of all elements

print(np.sum(b))
print(np.sum(b, axis=0))      #Column-wise
print(np.sum(b, axis=1))      #Row-wise

12
60
21
[5 7 9]
[ 6 15]


In [ ]:
#Logical indexing - Identify which elements fulfill the constraint
b = np.array([[1,2,3],[4,5,6]])
print(b > 2)

[[False False  True]
 [ True  True  True]]


In [ ]:
print(b[ b > 2 ])       #Extract the elements that fulfill the constraint

[3 4 5 6]


In [ ]:
b[ b > 2 ] = 100      #Replace where the constraints are fulfilled
print(b)

[[  1   2 100]
 [100 100 100]]


In [ ]:
#Iterating
arr = np.array([1, 2, 3])
for x in arr:
  print(x)

1
2
3


In [ ]:
#Print row by row
arr = np.array([[1, 2, 3], [4, 5, 6]])
for x in arr:
  print(x)

[1 2 3]
[4 5 6]


In [ ]:
#Print element by element
arr = np.array([[1, 2, 3], [4, 5, 6]])
for x in arr:
  for y in x:
    print(y)

1
2
3
4
5
6


In [ ]:
#linspace - Create a random array, same difference between the numbers
x = np.linspace(0, 100, 51)     #start, end, how many numbers
print(x)

[  0.   2.   4.   6.   8.  10.  12.  14.  16.  18.  20.  22.  24.  26.
  28.  30.  32.  34.  36.  38.  40.  42.  44.  46.  48.  50.  52.  54.
  56.  58.  60.  62.  64.  66.  68.  70.  72.  74.  76.  78.  80.  82.
  84.  86.  88.  90.  92.  94.  96.  98. 100.]


In [ ]:
x = np.linspace(0, 10, 8)     #No 8 integer values of same difference between 0 - 10
print(x)

[ 0.          1.42857143  2.85714286  4.28571429  5.71428571  7.14285714
  8.57142857 10.        ]


In [ ]:
#Element wise operation - same operation on every element at a time

print(x + 10)

[10.         11.42857143 12.85714286 14.28571429 15.71428571 17.14285714
 18.57142857 20.        ]


In [ ]:
y = np.array([1, 2, 3, 4])
z = np.array([10, 10, 20, 30])

print(y ** 2)
print(2*y + z)

[ 1  4  9 16]
[12 14 26 38]


# Pandas
* A Python library
* Used to analyze and manipulate data

# Data Analysis

In [ ]:
import pandas as pd

In [ ]:
data = {
  "Name": ['Arif', 'Nafis', 'Hasan'],
  "Age": [35, 30, 40]
}

#load data into a DataFrame [Formated data; 2 Dimensional Data Structure]
df = pd.DataFrame(data)

print(df)


In [ ]:
#loc attribute - accessing the dataframe values
print(df.loc[0])

In [ ]:
#Read csv
df = pd.read_csv('/content/lab1_data.csv')
print (df)          #Show first 5 and last 5 entries

In [ ]:
print (df.to_string())        #Show all entries

In [ ]:
#Analyzing data
print(df.head(10))        #Show first N entries

In [ ]:
print(df.tail())          #Show last 5 entries

In [ ]:
print(df.info())          #Information summary of all datas

In [ ]:
print(df.describe())        #More detailed information of all datas

In [ ]:
#Information of a specific column
print(df["Calories"].mean())
print(df["Calories"].median())
print(df["Calories"].mode())

#Data Cleaning

In [ ]:
#Drop rows with empty cells. Return a new Data Frame.
new_df = df.dropna()
print(new_df.to_string())

In [ ]:
#Replace NULL values with the mean value = 375
df.fillna(375, inplace = True)        #Inplace - Changes saved in the same Dataframe
print(df.to_string())

In [ ]:
#Replace in a specific column
df["Calories"].fillna(375, inplace = True)

In [ ]:
#Update data
df.loc[165, 'Duration'] = 45
print(df.to_string())

In [ ]:
#Duplicate data finding
print(df.duplicated().to_string())      #False - Unique, True - Duplicate values

In [ ]:
#Drop duplicate data
df.drop_duplicates(inplace = True)
print(df.duplicated().to_string())

In [ ]:
#correlation
df.corr()       # 0 - No relation, 1 - Strongly correlated, -1 - Strongly correlated but adversely

#Data Visualisation

In [ ]:
#plot data
df.plot()

In [ ]:
#Customise to make it more understandable
df.plot(kind = 'scatter', x = 'Duration', y = 'Calories')

In [ ]:
df.plot(kind = 'scatter', x = 'Duration', y = 'Maxpulse')

In [ ]:
df["Duration"].plot(kind = 'hist')